kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "node /home/runner/workspace/src/server.js"

[services.production]

[services.production.build]
args = ["echo", "no-build"]

[services.production.run]
args = ["node", "/home/runner/workspace/src/server.js"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/health"
