kind = "web"
previewPath = "/"
title = "Ilm API"
version = "1.0.0"
id = "artifacts/api-server"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22729

[services.env]
PORT = "22729"

[services.development]
run = "node /home/runner/workspace/src/server.js"

[services.production]

[services.production.build]
args = ["echo", "no-build"]

[services.production.run]
args = ["npm", "start"]

[services.production.run.env]
NODE_ENV = "production"

[services.production.health.startup]
path = "/health"
